version: '3'
services:
  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MYSQL_DB_NAME:test}
      MYSQL_USER: ${MYSQL_USER:root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:poli1234}

  # Spring Boot application service
  spring-app:
    image: your-docker-username/your-app-name:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: ${MYSQL_DB_NAME:test}
      MYSQL_USER: ${MYSQL_USER:root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:poli1234}