version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3307:3306"  # Usamos un puerto diferente para evitar conflictos si MySQL ya está instalado localmente
    environment:
      MYSQL_ROOT_PASSWORD: poli1234
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: poli1234

  spring-app:
    image: tu-usuario-docker/tu-app:latest
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: poli1234