name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Docker Image
        run: |
          docker build -t  push sjcmag/appsprint:v2 .
          docker login -u $username -p $password
          docker push push sjcmag/appsprint:v2

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose-file.yml up -d
